services:
  mariadb:
    image: mariadb:11.5
    container_name: hybridge_community_dev
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQLI_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQLI_DATABASE_NAME}"
      MYSQL_USER: "${MYSQLI_USER}"
      MYSQL_PASSWORD: "${MYSQLI_PASSWORD}"

    ports:
      - "2025:3306"
    
    volumes:
      - mariadb_data:/var/lib/mysql

    networks:
      - dev_network_community

volumes:
  mariadb_data:
    driver: local

networks:
  dev_network_community:
    driver: bridge